/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImagesListRouteImport } from './routes/images/list'
import { Route as ContainersListRouteImport } from './routes/containers/list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesListRoute = ImagesListRouteImport.update({
  id: '/images/list',
  path: '/images/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersListRoute = ContainersListRouteImport.update({
  id: '/containers/list',
  path: '/containers/list',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers/list': typeof ContainersListRoute
  '/images/list': typeof ImagesListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/containers/list': typeof ContainersListRoute
  '/images/list': typeof ImagesListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers/list': typeof ContainersListRoute
  '/images/list': typeof ImagesListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/containers/list' | '/images/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/containers/list' | '/images/list'
  id: '__root__' | '/' | '/containers/list' | '/images/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersListRoute: typeof ContainersListRoute
  ImagesListRoute: typeof ImagesListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/list': {
      id: '/images/list'
      path: '/images/list'
      fullPath: '/images/list'
      preLoaderRoute: typeof ImagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/list': {
      id: '/containers/list'
      path: '/containers/list'
      fullPath: '/containers/list'
      preLoaderRoute: typeof ContainersListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersListRoute: ContainersListRoute,
  ImagesListRoute: ImagesListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
